CREATE DATABASE IF NOT EXISTS Bank;
USE Bank;

CREATE TABLE IF NOT EXISTS CLIENT(
	name VARCHAR(60) NOT NULL,
	CIN VARCHAR(100) NOT NULL PRIMARY KEY,
	telephne INT NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	codePostale INT NOT NULL,
	city VARCHAR(255),
	dateNaissance DATETIME,
	sold float
);
CREATE TABLE IF NOT EXISTS Compte(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	clientCin VARCHAR(100),
   dateCreation DateTime NOT NULL,
   bank VARCHAR(255) NOT NULL,
   ville VARCHAR(255) NOT NULL,
   agence VARCHAR(255) NOT NULL,
   rib INT NOT NULL UNIQUE,
   type_compte ENUM('CompteCourant','CompteEpargne'),
   sold FLOAT
   CONSTRAINT fk_client FOREIGN KEY (clientCin) REFERENCES CLIENT(CIN) ON DELETE SET NULL
);
#DROP TABLE Compte;
#DROP TABLE CLIENT;
SELECT * FROM CLIENT;
SELECT *  FROM  Compte;