#CREATE DATABASE Bank;
USE Bank;

CREATE TABLE CLIENT(
	name VARCHAR(60) NOT NULL,
	CIN VARCHAR(100) NOT NULL PRIMARY KEY,
	telephne INT NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	codePostale INT NOT NULL,
	city VARCHAR(255),
	dateNaissance DATETIME,
	sold float
);
CREATE TABLE Compte(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	clientCin VARCHAR(100),
   dateCreation DateTime NOT NULL,
   bank VARCHAR(255) NOT NULL,
   ville VARCHAR(255) NOT NULL,
   agence VARCHAR(255) NOT NULL,
   rib INT NOT NULL UNIQUE,
   type_compte ENUM('CompteCourant','CompteEpargne'),
   sold FLOAT,
   CONSTRAINT fk_client FOREIGN KEY (clientCin) REFERENCES CLIENT(CIN) ON DELETE SET NULL
);

CREATE TABLE Transact(
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	sold FLOAT NOT NULL,
	montant FLOAT NOT NULL,
   rib INT NOT NULL UNIQUE,
   clientCin VARCHAR(100),
	id_compte INT,
	date_Transaction DATETIME DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT fk_clientCin FOREIGN KEY (clientCin) REFERENCES CLIENT(CIN) ON DELETE SET NULL,
	CONSTRAINT fk_Compte FOREIGN KEY (id_compte) REFERENCES Compte(id) ON DELETE SET NULL
);
#DROP TABLE Compte;
#DROP TABLE CLIENT;
SELECT * FROM CLIENT;
SELECT *  FROM  Compte;
SELECT *  FROM  Transact;